[package]
authors = ['Phala.network']
edition = '2018'
name = 'pallet-phala'
version = "2.0.0"
license = "Apache 2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", default-features = false, optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
frame-support = { version = "2.0.0", default-features = false, path = "../../substrate/frame/support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../substrate/frame/system" }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/runtime" }
sp-std = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/std" }
sp-io = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/io" }

chrono = { version = "0.4", default-features = false }
itertools = { version = "0.8", default-features = false }
untrusted = { version = "0.7" }
base64 = { version = "0.11", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false }
webpki = { path = "../../webpki", default_features = false }
serde_json_no_std = { path = "../../serde_json_no_std", version = "1.0", default-features = false, features = ["alloc"] }
# serde_json_core = {}
blake2-rfc = { version = "0.2.18", default-features = false }
libsecp256k1 = { version = "0.3.2", default-features = false }

[dependencies.pallet-balances]
default-features = false
version = "2.0.0"
path = "../../substrate/frame/balances"

[dev-dependencies]
sp-core = { version = "2.0.0", path = "../../substrate/primitives/core", default_features = false, features = ["full_crypto"] }
pallet-timestamp = { version = "2.0.0", path = "../../substrate/frame/timestamp" }
hex-literal = "0.3.1"
rand = "0.7.3"

[features]
default = ['std']
std = [
    "serde/std",
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "sp-io/std",
    "sp-std/std"
]
