name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      run: |
          rustup install nightly --profile default
          rustup +nightly target add wasm32-unknown-unknown

    - name: fmt
      run: cargo +nightly fmt --all -- --check

    - name: build
      run: cargo build --workspace --verbose

    - name: test
      run: cargo test --workspace --verbose -- --test-threads=1
