[workspace]
members = [".", "client", "proc-macro", "test-node"]

[package]
name = "substrate-subxt"
version = "0.12.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/paritytech/substrate-subxt"
documentation = "https://docs.rs/substrate-subxt"
homepage = "https://www.parity.io/"
description = "Submit extrinsics (transactions) to a substrate node via RPC"
keywords = ["parity", "substrate", "blockchain"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[features]
default = []
client = ["substrate-subxt-client"]

# enable this feature to run tests which require a local dev chain node
integration-tests = []

[dependencies]
log = "0.4.11"
thiserror = "1.0.20"
futures = "0.3.5"
jsonrpsee = { version = "0.1.0", features = ["ws"] }
num-traits = { version = "0.2.12", default-features = false }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
url = "2.1.1"
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false, features = ["derive", "full"] }

frame-metadata = { version = "12.0.0", package = "frame-metadata", path = "../substrate/frame/metadata" }
frame-support = { version = "2.0.0", package = "frame-support", path = "../substrate/frame/support" }
sp-runtime = { version = "2.0.0", package = "sp-runtime", path = "../substrate/primitives/runtime" }
sp-version = { version = "2.0.0", package = "sp-version", path = "../substrate/primitives/version" }
pallet-indices = { version = "2.0.0", package = "pallet-indices", path = "../substrate/frame/indices" }
hex = "0.4.2"
sp-std = { version = "2.0.0", path = "../substrate/primitives/std" }
application-crypto = { version = "2.0.0", package = "sp-application-crypto", path = "../substrate/primitives/application-crypto" }
sp-finality-grandpa = { version = "2.0.0", path = "../substrate/primitives/finality-grandpa" }
sp-consensus-babe = { version = "0.8.0", path = "../substrate/primitives/consensus/babe" }
pallet-im-online = { version = "2.0.0", path = "../substrate/frame/im-online" }
sp-authority-discovery = { version = "2.0.0", path = "../substrate/primitives/authority-discovery" }
pallet-staking = { version = "2.0.0", package = "phala-staking", path = "../pallets/staking" }

sp-rpc = { version = "2.0.0", package = "sp-rpc", path = "../substrate/primitives/rpc" }
sp-core = { version = "2.0.0", package = "sp-core", path = "../substrate/primitives/core" }
sc-rpc-api = { version = "0.8.0", package = "sc-rpc-api", path = "../substrate/client/rpc-api" }
sp-transaction-pool = { version = "2.0.0", package = "sp-transaction-pool", path = "../substrate/primitives/transaction-pool" }
substrate-subxt-client = { version = "0.4.0", path = "client", optional = true }
substrate-subxt-proc-macro = { version = "0.12.0", path = "proc-macro" }

[dev-dependencies]
async-std = { version = "1.6.4", features = ["attributes"] }
env_logger = "0.7.1"
frame-system = { version = "2.0.0", package = "frame-system", path = "../substrate/frame/system" }
pallet-balances = { version = "2.0.0", package = "pallet-balances", path = "../substrate/frame/balances" }
sp-keyring = { version = "2.0.0", package = "sp-keyring", path = "../substrate/primitives/keyring" }
substrate-subxt-client = { version = "0.4.0", path = "client" }
tempdir = "0.3.7"
test-node = { path = "test-node" }
wabt = "0.10.0"
assert_matches = "1.3"
